#!/bin/bash
set -eu
PROJECT_ID="${PROJECT_ID:-aimhi-analyzer-sandbox}"
REGION="${REGION:-us-central1}"
DATASET_ID="${DATASET_ID:-autonomy_telemetry}"
TABLE_ID="${TABLE_ID:-events}"
SINK_NAME="${SINK_NAME:-autonomy-telemetry-sink}"
SERVICE_ACCOUNT_EMAIL="${SERVICE_ACCOUNT_EMAIL:-coding-agent@aimhi-analyzer-sandbox.iam.gserviceaccount.com}"
LOGGING_WRITER="service-784473183307@gcp-sa-logging.iam.gserviceaccount.com"
gcloud config set project "$PROJECT_ID"
"$(dirname "$0")/apply-iam-bindings.sh" "$PROJECT_ID" "$DATASET_ID"
"$(dirname "$0")/apply-bigquery-schema.sh" "$PROJECT_ID" "$DATASET_ID" "$TABLE_ID"
"$(dirname "$0")/apply-logging-sink.sh" "$PROJECT_ID" "$DATASET_ID" "$SINK_NAME"
"$(dirname "$0")/deploy-cloud-run.sh" "$PROJECT_ID" "$REGION" "$SERVICE_ACCOUNT_EMAIL"
"$(dirname "$0")/deploy-cloud-function.sh" "$PROJECT_ID" "$REGION" "$SERVICE_ACCOUNT_EMAIL"
"$(dirname "$0")/deploy-dashboards.sh" "$PROJECT_ID"
"$(dirname "$0")/deploy-looker-model.sh" "$PROJECT_ID"
"$(dirname "$0")/../pipelines/autonomy-chaos-pipeline.sh" "$PROJECT_ID"
"$(dirname "$0")/../pipelines/autonomy-canary-pipeline.sh" "$PROJECT_ID"
"$(dirname "$0")/../pipelines/autonomy-ux-pipeline.sh" "$PROJECT_ID"
"$(dirname "$0")/../pipelines/autonomy-security-pipeline.sh" "$PROJECT_ID"
"$(dirname "$0")/../pipelines/autonomy-drift-pipeline.sh" "$PROJECT_ID"
"$(dirname "$0")/../pipelines/autonomy-master-pipeline.sh" "$PROJECT_ID"
echo "Autonomy deployment complete for $PROJECT_ID"
