steps:
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "gcr.io/$PROJECT_ID/autonomy-emitter:latest", "infra/autonomy/telemetry"]
- name: gcr.io/cloud-builders/docker
  args: ["push", "gcr.io/$PROJECT_ID/autonomy-emitter:latest"]
